extern int next(void);
int next2(void) {return next();}

void throw_exception(int x)
{
    throw x;
}